### ISSUE TITLE
add zip and cwebp for post processing

### ISSUE THREAD

**Issue by cwhits** [docker-hotio/docker-mylar3#9]
Mylar has the ability to run custom post processing scripts but the amount we can do is pretty limited since `zip` and `cwebp` are missing.

Any chance of adding `zip` and `libwebp-tools` to the image? 

If not, any tips on adding them myself (outside of execing into the container every update and adding them)?

**Comment by cwhits** [comment]
As an example, I'm looking to add a post-processing script that uses `zip` to unzip the files, delete z*.jpg, convert jpg to webp, and then zip the file back up.

**Comment by hotio** [comment]
https://hotio.dev/containers/mylar3/#executing-your-own-scripts

**Comment by cwhits** [comment]
so just attach this to `/etc/cont-finish.d/99-my-script`?
```
#!/usr/bin/with-contenv bash
apk add zip libwebp-tools
```

**Comment by hotio** [comment]
cont-init.d

**Comment by cwhits** [comment]
Thanks!
